[tool.poetry]
name = "carify"
version = "0.1.0"
description = ""
authors = ["kevenmiano <k_l.s@outlook.com>"]
readme = "README.md"
packages = [{include = "carify"}]

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.2"
flask-cors = "^6.0.1"
python-dotenv = "^1.0.0"
pydantic = "^2.0.0"
pydantic-extra-types = "^2.0.0"
email-validator = "^2.0.0"
spectree = "^1.2.0"
returns = "^0.23.0"
opentelemetry-api = "^1.27.0"
opentelemetry-sdk = "^1.27.0"
opentelemetry-instrumentation-flask = "^0.48b0"
opentelemetry-exporter-otlp = "^1.27.0"
opentelemetry-instrumentation-logging = "^0.48b0"
gunicorn = "^22.0.0"

[tool.poetry.group.dev.dependencies]
faker = "^28.0.0"
setuptools = "<81"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
