CREATE DATABASE IF NOT EXISTS carify;
USE carify;

CREATE TABLE IF NOT EXISTS Proprietarios (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Telefone VARCHAR(15) NOT NULL,
    Documento VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Fabricantes (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Veiculos (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Ano INT NOT NULL,
    Cor TEXT NOT NULL,
    Placa VARCHAR(7) NOT NULL UNIQUE,
    ProprietarioID INT NOT NULL,
    FabricanteID INT NOT NULL,
    FOREIGN KEY (ProprietarioID) REFERENCES Proprietarios(ID),
    FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID)
);

CREATE TABLE IF NOT EXISTS Servicos (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Descricao TEXT NOT NULL,
    Preco DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS Vendas (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DataCriacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataAtualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DataCancelamento TIMESTAMP NULL,
    ProprietarioID INT NOT NULL,
    VeiculoID INT NOT NULL,
    ServicoID INT NOT NULL,
    Total DECIMAL(18, 2) NOT NULL,
    FOREIGN KEY (ServicoID) REFERENCES Servicos(ID),
    FOREIGN KEY (ProprietarioID) REFERENCES Proprietarios(ID),
    FOREIGN KEY (VeiculoID) REFERENCES Veiculos(ID)
);
